import os

BASE_DIR = r"C:\Users\Mark\Desktop\A & E Auto Upholstery Website Rebuild"

cities = [
    ("Cape Canaveral",      "cape-canaveral"),
    ("Cocoa",               "cocoa"),
    ("Cocoa Beach",         "cocoa-beach"),
    ("Grant-Valkaria",      "grant-valkaria"),
    ("Indian Harbour Beach", "indian-harbour-beach"),
    ("Indialantic",         "indialantic"),
    ("Malabar",             "malabar"),
    ("Melbourne",           "melbourne"),
    ("Melbourne Beach",     "melbourne-beach"),
    ("Melbourne Village",   "melbourne-village"),
    ("Palm Bay",            "palm-bay"),
    ("Palm Shores",         "palm-shores"),
    ("Rockledge",           "rockledge"),
    ("Satellite Beach",     "satellite-beach"),
    ("Titusville",          "titusville"),
    ("West Melbourne",      "west-melbourne"),
]

SHOP_IMG = "https://pbrlhyansxjdndccwtau.supabase.co/storage/v1/object/public/media-public/aee7c2b2-a574-4e23-a4b1-32928356d9b5/0f7f7712-5ad1-4392-bbf8-7cf41634cb5a/1777007141536_ae-auto-upholstery-shop.jpg"
PATTERN_BG = "https://pbrlhyansxjdndccwtau.supabase.co/storage/v1/object/public/media-public/aee7c2b2-a574-4e23-a4b1-32928356d9b5/root/1776951781283_upholstery-pattern-background.png"
LOGO = "https://pbrlhyansxjdndccwtau.supabase.co/storage/v1/object/public/media-public/aee7c2b2-a574-4e23-a4b1-32928356d9b5/root/1776686441300_ae-auto-upholstery-logo.png"

def make_page(city, slug):
    alt_text = f"A&amp;E Auto Upholstery shop entrance, providing expert boat and vehicle interior restoration to residents of {city} and throughout Brevard County since 1962."
    body_text = (
        f"When {city} residents need expert upholstery work, they turn to A&amp;E Auto and Boat Upholstery. "
        f"As a 4th generation family-owned business serving Brevard County since 1962, we&#8217;ve built our "
        f"reputation on handcrafted quality and personal service. We specialize in auto, RV, boat, and motorcycle "
        f"upholstery &#8212; handling every project with care from our Melbourne, FL shop. "
        f"Call us at (321) 254-6597 for a free quote."
    )
    canonical = f"https://www.aeautoupholstery.com/{slug}.html"
    title = f"Auto Upholstery {city} FL | A&amp;E Auto and Boat Upholstery"
    description = f"Looking for expert auto, boat, or motorcycle upholstery near {city}, FL? A&amp;E Auto and Boat Upholstery has served Brevard County since 1962. Call (321) 254-6597."

    lines = []
    lines.append('<!DOCTYPE html>')
    lines.append('<html lang="en">')
    lines.append('<head>')
    lines.append('  <meta charset="UTF-8">')
    lines.append('  <meta name="viewport" content="width=device-width, initial-scale=1.0">')
    lines.append('')
    lines.append(f'  <title>{title}</title>')
    lines.append(f'  <meta name="description" content="{description}">')
    lines.append('  <meta name="author" content="A &amp; E Auto and Boat Upholstery">')
    lines.append('  <meta name="language" content="en">')
    lines.append(f'  <link rel="canonical" href="{canonical}">')
    lines.append('')
    lines.append('  <meta property="og:type" content="website">')
    lines.append('  <meta property="og:site_name" content="A &amp; E Auto and Boat Upholstery">')
    lines.append(f'  <meta property="og:title" content="{title}">')
    lines.append(f'  <meta property="og:description" content="{description}">')
    lines.append(f'  <meta property="og:url" content="{canonical}">')
    lines.append(f'  <meta property="og:image" content="{LOGO}">')
    lines.append('  <meta property="og:image:alt" content="A&amp;E Auto Upholstery company logo">')
    lines.append('')
    lines.append('  <meta name="twitter:card" content="summary_large_image">')
    lines.append(f'  <meta name="twitter:title" content="{title}">')
    lines.append(f'  <meta name="twitter:description" content="{description}">')
    lines.append(f'  <meta name="twitter:url" content="{canonical}">')
    lines.append(f'  <meta name="twitter:image" content="{LOGO}">')
    lines.append('  <meta name="twitter:image:alt" content="A&amp;E Auto Upholstery company logo">')
    lines.append('')
    lines.append('  <link rel="preconnect" href="https://fonts.googleapis.com">')
    lines.append('  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>')
    lines.append('  <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700;800&family=Open+Sans:wght@400;500;600&display=swap" rel="stylesheet">')
    lines.append('  <link rel="stylesheet" href="css/styles.css">')
    lines.append('  <link rel="stylesheet" href="css/animations.css">')
    lines.append('</head>')
    lines.append('<body data-page="areas">')
    lines.append('')
    lines.append('  <!-- HEADER -->')
    lines.append('  <header class="site-header" id="site-header">')
    lines.append('    <div class="header-inner container">')
    lines.append('      <a href="index.html" class="header-logo" aria-label="A &amp; E Auto Upholstery &#8212; Home">')
    lines.append(f'        <img src="{LOGO}"')
    lines.append('             alt="A&amp;E Auto Upholstery company logo" width="180" loading="eager">')
    lines.append('      </a>')
    lines.append('      <nav class="site-nav" id="site-nav" role="navigation" aria-label="Main navigation">')
    lines.append('        <ul class="nav-list">')
    lines.append('          <li class="nav-item"><a href="index.html" class="nav-link" data-nav="home">Home</a></li>')
    lines.append('          <li class="nav-item"><a href="about.html" class="nav-link" data-nav="about">About</a></li>')
    lines.append('          <li class="nav-item nav-dropdown" id="services-dropdown">')
    lines.append('            <button class="nav-dropdown-toggle" aria-haspopup="true" aria-expanded="false" aria-controls="services-menu" data-nav="services">')
    lines.append('              Services <span class="dropdown-arrow" aria-hidden="true">&#9660;</span>')
    lines.append('            </button>')
    lines.append('            <ul class="dropdown-menu" id="services-menu" role="menu">')
    lines.append('              <li role="none"><a href="auto-rv.html" class="dropdown-link" role="menuitem">Auto &amp; RV</a></li>')
    lines.append('              <li role="none"><a href="boat.html" class="dropdown-link" role="menuitem">Boat</a></li>')
    lines.append('              <li role="none"><a href="classic-car-restoration.html" class="dropdown-link" role="menuitem">Classic Car Restoration</a></li>')
    lines.append('              <li role="none"><a href="motorcycle.html" class="dropdown-link" role="menuitem">Motorcycle</a></li>')
    lines.append('            </ul>')
    lines.append('          </li>')
    lines.append('          <li class="nav-item"><a href="gallery.html" class="nav-link" data-nav="gallery">Gallery</a></li>')
    lines.append('          <li class="nav-item nav-dropdown" id="areas-dropdown">')
    lines.append('            <button class="nav-dropdown-toggle" aria-haspopup="true" aria-expanded="false" aria-controls="areas-menu" data-nav="areas">')
    lines.append('              Areas We Serve <span class="dropdown-arrow" aria-hidden="true">&#9660;</span>')
    lines.append('            </button>')
    lines.append('            <ul class="dropdown-menu" id="areas-menu" role="menu">')
    lines.append('              <li role="none"><a href="cape-canaveral.html" class="dropdown-link" role="menuitem">Cape Canaveral</a></li>')
    lines.append('              <li role="none"><a href="cocoa.html" class="dropdown-link" role="menuitem">Cocoa</a></li>')
    lines.append('              <li role="none"><a href="cocoa-beach.html" class="dropdown-link" role="menuitem">Cocoa Beach</a></li>')
    lines.append('              <li role="none"><a href="grant-valkaria.html" class="dropdown-link" role="menuitem">Grant-Valkaria</a></li>')
    lines.append('              <li role="none"><a href="indian-harbour-beach.html" class="dropdown-link" role="menuitem">Indian Harbour Beach</a></li>')
    lines.append('              <li role="none"><a href="indialantic.html" class="dropdown-link" role="menuitem">Indialantic</a></li>')
    lines.append('              <li role="none"><a href="malabar.html" class="dropdown-link" role="menuitem">Malabar</a></li>')
    lines.append('              <li role="none"><a href="melbourne.html" class="dropdown-link" role="menuitem">Melbourne</a></li>')
    lines.append('              <li role="none"><a href="melbourne-beach.html" class="dropdown-link" role="menuitem">Melbourne Beach</a></li>')
    lines.append('              <li role="none"><a href="melbourne-village.html" class="dropdown-link" role="menuitem">Melbourne Village</a></li>')
    lines.append('              <li role="none"><a href="palm-bay.html" class="dropdown-link" role="menuitem">Palm Bay</a></li>')
    lines.append('              <li role="none"><a href="palm-shores.html" class="dropdown-link" role="menuitem">Palm Shores</a></li>')
    lines.append('              <li role="none"><a href="rockledge.html" class="dropdown-link" role="menuitem">Rockledge</a></li>')
    lines.append('              <li role="none"><a href="satellite-beach.html" class="dropdown-link" role="menuitem">Satellite Beach</a></li>')
    lines.append('              <li role="none"><a href="titusville.html" class="dropdown-link" role="menuitem">Titusville</a></li>')
    lines.append('              <li role="none"><a href="west-melbourne.html" class="dropdown-link" role="menuitem">West Melbourne</a></li>')
    lines.append('            </ul>')
    lines.append('          </li>')
    lines.append('          <li class="nav-item"><a href="contact.html" class="nav-link" data-nav="contact">Contact</a></li>')
    lines.append('        </ul>')
    lines.append('      </nav>')
    lines.append('      <button class="hamburger-btn" id="hamburger-btn" aria-label="Open navigation menu" aria-expanded="false" aria-controls="site-nav">')
    lines.append('        <span class="hamburger-line"></span>')
    lines.append('        <span class="hamburger-line"></span>')
    lines.append('        <span class="hamburger-line"></span>')
    lines.append('      </button>')
    lines.append('    </div>')
    lines.append('  </header>')
    lines.append('  <!-- END HEADER -->')
    lines.append('')
    lines.append('  <main id="main-content">')
    lines.append('')
    lines.append('    <!-- HERO -->')
    lines.append('    <section class="hero hero--city" aria-label="' + city + ' hero">')
    lines.append('      <div class="hero-bg" aria-hidden="true"></div>')
    lines.append('      <div class="hero-overlay" aria-hidden="true"></div>')
    lines.append('      <div class="container hero-content">')
    lines.append(f'        <h1 class="hero-heading">A&amp;E Auto Upholstery is {city}&#8217;s Best Choice!</h1>')
    lines.append('        <div class="hero-buttons">')
    lines.append('          <a href="contact.html" class="btn btn--gold btn--lg">Get a Quote</a>')
    lines.append('          <a href="tel:+13212546597" class="btn--phone">')
    lines.append('            <span class="btn-label">Call Now</span>')
    lines.append('            <span class="btn-number">(321) 254-6597</span>')
    lines.append('          </a>')
    lines.append('        </div>')
    lines.append('      </div>')
    lines.append('    </section>')
    lines.append('    <!-- END HERO -->')
    lines.append('')
    lines.append('    <!-- LOCATION & HOURS -->')
    lines.append('    <section class="section section--alt" aria-labelledby="location-heading">')
    lines.append('      <div class="container" style="text-align:center;">')
    lines.append('        <h2 class="section-heading text-center" id="location-heading">Visit Our Shop</h2>')
    lines.append('        <div class="gold-divider gold-divider--center"></div>')
    lines.append('        <address style="font-style:normal;color:var(--color-white);line-height:1.9;max-width:480px;margin:0 auto;">')
    lines.append('          <p>1668 N Harbor City Blvd<br>Melbourne, FL 32935</p>')
    lines.append('          <p><a href="tel:+13212546597" style="color:var(--color-gold);">(321) 254-6597</a></p>')
    lines.append('          <p><a href="mailto:info@aeautoupholstery.com" style="color:var(--color-gold);">info@aeautoupholstery.com</a></p>')
    lines.append('          <p><strong style="color:var(--color-white);">Hours:</strong><br>Monday &ndash; Friday<br>8:00am &ndash; 5:30pm EST</p>')
    lines.append('        </address>')
    lines.append('      </div>')
    lines.append('    </section>')
    lines.append('    <!-- END LOCATION & HOURS -->')
    lines.append('')
    lines.append('    <!-- ABOUT / BEST CHOICE -->')
    lines.append('    <section class="section section--upholstery-bg"')
    lines.append(f'             style="background-image:url(\'{PATTERN_BG}\');background-size:cover;background-position:center;background-attachment:fixed;"')
    lines.append('             aria-labelledby="about-heading">')
    lines.append('      <div class="container">')
    lines.append('        <div class="city-about-grid">')
    lines.append(f'          <img src="{SHOP_IMG}"')
    lines.append(f'               alt="{alt_text}"')
    lines.append('               loading="lazy">')
    lines.append('          <div class="city-about-box">')
    lines.append(f'            <h2 id="about-heading">Why {city} Chooses A&amp;E</h2>')
    lines.append(f'            <p>{body_text}</p>')
    lines.append('          </div>')
    lines.append('        </div>')
    lines.append('      </div>')
    lines.append('    </section>')
    lines.append('    <!-- END ABOUT / BEST CHOICE -->')
    lines.append('')
    lines.append('    <!-- CONTACT FORM -->')
    lines.append('    <section class="section" aria-labelledby="contact-form-heading">')
    lines.append('      <div class="container">')
    lines.append('        <h2 class="section-heading text-center" id="contact-form-heading">Contact Us</h2>')
    lines.append('        <div class="gold-divider gold-divider--center"></div>')
    lines.append('        <div class="contact-embed">')
    lines.append('          <iframe src="https://hyppohq.io/f/contact-us-ae-auto-upholstery?embed=true&amp;theme=light" style="width:100%;min-height:600px;border:none;" allowfullscreen loading="lazy" title="Contact A &amp; E Auto and Boat Upholstery"></iframe>')
    lines.append('        </div>')
    lines.append('      </div>')
    lines.append('    </section>')
    lines.append('    <!-- END CONTACT FORM -->')
    lines.append('')
    lines.append('    <!-- TESTIMONIALS -->')
    lines.append('    <section class="testimonials-section section section--alt" aria-label="Customer testimonials">')
    lines.append('      <div class="container">')
    lines.append('        <h2 class="section-heading text-center">Testimonials!</h2>')
    lines.append('        <div class="gold-divider gold-divider--center"></div>')
    lines.append('        <div class="reviews-embed">')
    lines.append('          <iframe src="https://hyppohq.io/w/ae-auto-google-reviews?embed=true" style="width:100%;min-height:510px;border:none;" allowfullscreen title="Google Reviews for A &amp; E Auto and Boat Upholstery" loading="lazy"></iframe>')
    lines.append('        </div>')
    lines.append('        <div style="text-align:center;margin-top:var(--space-8);">')
    lines.append('          <a href="tel:+13212546597" class="btn--phone">')
    lines.append('            <span class="btn-label">Call Now</span>')
    lines.append('            <span class="btn-number">(321) 254-6597</span>')
    lines.append('          </a>')
    lines.append('        </div>')
    lines.append('      </div>')
    lines.append('    </section>')
    lines.append('    <!-- END TESTIMONIALS -->')
    lines.append('')
    lines.append('    <!-- MAP -->')
    lines.append('    <section class="section" aria-labelledby="map-heading">')
    lines.append('      <div class="container">')
    lines.append('        <h2 class="section-heading text-center" id="map-heading">Find Us Here</h2>')
    lines.append('        <div class="gold-divider gold-divider--center"></div>')
    lines.append('        <iframe src="https://maps.google.com/maps?q=1668+N+Harbor+City+Blvd,+Melbourne,+FL+32935&amp;t=&amp;z=15&amp;ie=UTF8&amp;iwloc=&amp;output=embed"')
    lines.append('                style="width:100%;height:450px;border:none;border-radius:var(--radius-md);display:block;"')
    lines.append('                allowfullscreen loading="lazy" title="A &amp; E Auto and Boat Upholstery location &#8212; 1668 N Harbor City Blvd, Melbourne, FL 32935"></iframe>')
    lines.append('      </div>')
    lines.append('    </section>')
    lines.append('    <!-- END MAP -->')
    lines.append('')
    lines.append('    <!-- CTA SECTION -->')
    lines.append('    <section class="cta-section" aria-label="Contact call to action">')
    lines.append('      <div class="container cta-inner">')
    lines.append('        <div class="cta-text">')
    lines.append('          <h2>Need Upholstery Done Right?</h2>')
    lines.append('          <p>From classic car seats to custom boat interiors, A &amp; E delivers craftsmanship you can feel. Family-owned since 1962, serving Melbourne and all of Brevard County.</p>')
    lines.append('        </div>')
    lines.append('        <div class="cta-buttons">')
    lines.append('          <a href="contact.html" class="btn btn--gold btn--lg">Get a Free Estimate</a>')
    lines.append('          <a href="tel:+13212546597" class="btn--phone">')
    lines.append('            <span class="btn-label">Call Now</span>')
    lines.append('            <span class="btn-number">(321) 254-6597</span>')
    lines.append('          </a>')
    lines.append('        </div>')
    lines.append('      </div>')
    lines.append('    </section>')
    lines.append('    <!-- END CTA -->')
    lines.append('')
    lines.append('  </main>')
    lines.append('')
    lines.append('  <!-- FOOTER -->')
    lines.append('  <footer class="site-footer">')
    lines.append('    <div class="container">')
    lines.append('      <div class="footer-grid">')
    lines.append('        <div class="footer-logo">')
    lines.append('          <a href="index.html" aria-label="A &amp; E Auto Upholstery &#8212; Home">')
    lines.append(f'            <img src="{LOGO}"')
    lines.append('                 alt="A&amp;E Auto Upholstery company logo" width="160" loading="lazy">')
    lines.append('          </a>')
    lines.append('          <p class="footer-tagline">Proudly serving Melbourne, FL since 1962.</p>')
    lines.append('        </div>')
    lines.append('        <div class="footer-contact">')
    lines.append('          <h3 class="footer-heading">Contact Us</h3>')
    lines.append('          <address>')
    lines.append('            <p>1668 N Harbor City Blvd<br>Melbourne, FL 32935</p>')
    lines.append('            <p><a href="tel:+13212546597">(321) 254-6597</a></p>')
    lines.append('            <p><a href="mailto:info@aeautoupholstery.com">info@aeautoupholstery.com</a></p>')
    lines.append('            <p><strong style="color:var(--color-white);">Hours:</strong><br>Monday &ndash; Friday<br>8:00am &ndash; 5:30pm EST</p>')
    lines.append('          </address>')
    lines.append('        </div>')
    lines.append('        <div class="footer-social">')
    lines.append('          <h3 class="footer-heading">Follow Us</h3>')
    lines.append('          <ul class="social-list">')
    lines.append('            <li>')
    lines.append('              <a href="https://www.facebook.com/AEUpholstery1/" target="_blank" rel="noopener noreferrer" class="social-link" aria-label="A &amp; E Auto Upholstery on Facebook">')
    lines.append('                <svg class="social-icon" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor"><path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z"/></svg>')
    lines.append('                <span>Facebook</span>')
    lines.append('              </a>')
    lines.append('            </li>')
    lines.append('            <li>')
    lines.append('              <a href="https://www.instagram.com/aeautoupholstery/" target="_blank" rel="noopener noreferrer" class="social-link" aria-label="A &amp; E Auto Upholstery on Instagram">')
    lines.append('                <svg class="social-icon" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="2" y="2" width="20" height="20" rx="5" ry="5"/><path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z"/><line x1="17.5" y1="6.5" x2="17.51" y2="6.5"/></svg>')
    lines.append('                <span>Instagram</span>')
    lines.append('              </a>')
    lines.append('            </li>')
    lines.append('            <li>')
    lines.append('              <a href="https://www.yelp.com/biz/a-and-e-auto-and-boat-upholstery-melbourne?dd_referrer=" target="_blank" rel="noopener noreferrer" class="social-link" aria-label="A &amp; E Auto Upholstery on Yelp">')
    lines.append('                <svg class="social-icon" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor"><path d="M20.16 12.594l-4.995 1.433c-.96.275-1.75-.8-1.214-1.686l2.801-4.637c.53-.878 1.73-.773 2.115.173l1.293 3.204c.297.735-.09 1.527-.85 1.722h.85zM11.712 18.318l-1.12 4.99c-.21.94.697 1.73 1.605 1.435l4.774-1.606c.907-.306 1.12-1.47.367-2.062L13.2 18.35c-.756-.592-1.7-.21-1.488.705v-.737zm-3.434-2.856L3.66 17.22c-.923.195-1.21 1.374-.476 1.972l3.94 3.04c.735.566 1.77.038 1.79-.892l.12-5.122c.02-.93-.977-1.44-1.756-1.273v.317zm.066-4.802L3.93 8.47c-.807-.503-.69-1.688.188-2.01l4.643-1.724c.878-.326 1.765.418 1.63 1.345l-.733 5.02c-.136.926-1.15 1.323-1.854.758l-.456-.4zm5.46-5.27l-.09-5.23c-.016-.944-1.045-1.476-1.813-.94L8.46 2.553c-.766.537-.735 1.688.057 2.177l4.37 2.74c.793.497 1.822-.062 1.918-.98z"/></svg>')
    lines.append('                <span>Yelp</span>')
    lines.append('              </a>')
    lines.append('            </li>')
    lines.append('          </ul>')
    lines.append('        </div>')
    lines.append('      </div>')
    lines.append('    </div>')
    lines.append('    <div class="footer-bottom">')
    lines.append('      <div class="container">')
    lines.append('        <div class="footer-bottom-inner">')
    lines.append('          <div class="footer-legal">')
    lines.append('            <a href="privacy-policy.html">Privacy Policy</a>')
    lines.append('            <span aria-hidden="true">|</span>')
    lines.append('            <a href="terms-of-service.html">Terms of Service</a>')
    lines.append('          </div>')
    lines.append('          <p class="footer-copyright">&copy; <span id="footer-year"></span> A &amp; E Auto and Boat Upholstery. All rights reserved.</p>')
    lines.append('          <p class="footer-powered">Powered by <a href="https://hyppohq.ai/" target="_blank" rel="noopener noreferrer">HyppoAI</a></p>')
    lines.append('        </div>')
    lines.append('      </div>')
    lines.append('    </div>')
    lines.append('  </footer>')
    lines.append('  <!-- END FOOTER -->')
    lines.append('')
    lines.append('  <!-- CHAT WIDGET -->')
    lines.append("  <script>setTimeout(function(){var s=document.createElement('script');s.src='https://hyppohq.io/api/v1/widgets/embed/chat-with-us';s.async=true;document.body.appendChild(s);},3000);</script>")
    lines.append('')
    lines.append('  <script src="js/main.js" defer></script>')
    lines.append('</body>')
    lines.append('</html>')

    return '\n'.join(lines) + '\n'

created = []
for city, slug in cities:
    path = os.path.join(BASE_DIR, f"{slug}.html")
    content = make_page(city, slug)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    created.append(f"{slug}.html")
    print(f"Created: {slug}.html")

print(f"\nDone - {len(created)} files created.")
